language: scala
scala:
- 2.11.12
- 2.12.5
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.12.5"'
    tags: true
env:
  global:
  - secure: S3rLmHxmFxGS5G7XgaGck8Wi6QnIlFPaJMO5t6BDg8ggrsTseEB0CJPxBRHy+Xrg6J7N3AjmhOyz+ed3Z4rPHTxdF+20c6sGGvgTZCs6ngM7m+cqcJ7CczrEs0ZBJ9q5nUhBwb4nCYSqZ1UcE2JxZeKkfjhwYEFkRgZ0BL6f6Gw=
  - secure: bo8weR41K85HdydXWhMO1f8bYnxr8KpJOkhAly2NV3DIIp9HVRIMDx0apY08qkhH76JIWi1ck5EeoAzBLAMyzLrrmnFXojyFC0cbT66NdiHRHsuB/WEJ/Y+Qm03X4xwBA5JEIUC2ZeL+AwMrgeCohCqzHMxMbKWK6AObrvbvtXY=
  - SONA_USER=snowplow
  - secure: XrCLLEycNDpOnuAPHin3/2LgfyYdIOS52pwGi3moFWUdyeDjyTtLC8Wsa5iWi4zLRVox5FJLUzbp1GRf+jv/oGktXGqoLop7PZpCxxKlxtwQDYNqgJy4Ga8N6uLlxS7nUu39B75Mo3FftMAwetw0v/BE1jkotkwW283t+1AnBgE=
